import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { parseCookies } from "../helpers/";

import { useState } from "react";
import React from "react";

import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Card from "@mui/material/Card";
import CardActions from "@mui/material/CardActions";
import CardContent from "@mui/material/CardContent";
import Button from "@mui/material/Button";
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";

import Link from "next/link";

import Nav from "../components/Nav";

class Home extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      projects: [],
      last_retrieved: null,
    };
  }

  componentDidMount() {
    getProjects(false).then((projects) => {
      const oldProjects = this.state.projects;
      const mergedProjects = oldProjects.concat(projects.projects);

      this.setState({
        projects: mergedProjects,
        last_retrieved: projects.last_retrieved,
        hasNext: projects.hasNext,
      });
    });
  }

  render() {
    return (
      <div>
        <Head>
          <title>Show Execute Big</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Nav />
          <Container maxWidth="lg">
            <Grid container spacing={2} sx={{ mt: 2 }}>
              {this.state.projects &&
                this.state.projects.map((p) => (
                  <Grid item xs={4} key={p.key}>
                    <Card variant="outlined">
                      <CardContent>
                        <h1>{p.name}</h1>
                        <p>By {p.user.handle}</p>
                      </CardContent>
                      <CardActions>
                        {p.demo && (
                          <Button size="medium">
                            <Link href={p.demo}>
                              <a target="_blank">Demo</a>
                            </Link>
                          </Button>
                        )}
                        {p.source && (
                          <Button size="medium">
                            <Link href={p.source}>
                              <a target="_blank">Source</a>
                            </Link>
                          </Button>
                        )}
                      </CardActions>
                    </Card>
                  </Grid>
                ))}
            </Grid>

            {this.state.hasNext && (
              <Button
                onClick={async () => {
                  const projects = await getProjects(this.state.last_retrieved);
                  const oldProjects = this.state.projects;

                  const mergedProjects = oldProjects.concat(projects.projects);

                  this.setState({
                    projects: mergedProjects,
                    last_retrieved: projects.last_retrieved,
                    hasNext: projects.hasNext,
                  });
                }}
                size="large"
              >
                Load More
              </Button>
            )}
          </Container>
        </main>
      </div>
    );
  }
}

async function getProjects(last) {
  const projectResponse = await fetch(
    process.env.BASE_URL + "/api/projects" + (last ? "?last=" + last : "")
  );
  const data = await projectResponse.json();

  return data;
}

export default Home;
