import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { parseCookies } from "../helpers/";

import { useState } from "react";

import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Card from "@mui/material/Card";
import CardActions from "@mui/material/CardActions";
import CardContent from "@mui/material/CardContent";
import Button from "@mui/material/Button";
import Container from "@mui/material/Container";

import Link from "next/link";

export default function Home({ projects }) {

  return (
    <div>
      <Head>
        <title>Show Execute Big</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box sx={{ flexGrow: 1 }}>
          <AppBar position="static">
            <Toolbar>
              <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                Show Execute Big
              </Typography>
            </Toolbar>
          </AppBar>
        </Box>

        <Container maxWidth="sm">
          {projects && projects.map((p) => (
            <Card variant="outlined" sx={{ m: 2 }}>
              <CardContent>
                <h1>{p.name}</h1>
              </CardContent>
              <CardActions>
                {p.demo && (<Button size="medium"><Link href={p.demo}>Demo</Link></Button>)}
                {p.source && (<Button size="medium"><Link href={p.source}>Source</Link></Button>)}
              </CardActions>
            </Card>
          ))}
        </Container>
      </main>
    </div>
  );
}

Home.getInitialProps = async ({ req, res }) => {
  // get active batches
  const projectResponse = await fetch(process.env.APP_URL + "/api/projects");
  const projects = await projectResponse.json();

  console.log(projects);

  return {
    projects
  };
};
