import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { parseCookies } from "../helpers/";

import { useState } from "react";

import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Card from "@mui/material/Card";
import CardActions from "@mui/material/CardActions";
import CardContent from "@mui/material/CardContent";
import Button from "@mui/material/Button";
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";

import Link from "next/link";

import Nav from "../components/Nav";

export default function Home({ projects }) {

  return (
    <div>
      <Head>
        <title>Show Execute Big</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav />

        <Container maxWidth="lg">
            <Grid container spacing={2} sx={{mt: 2}}>
            {projects && projects.map((p) => (
                <Grid item xs={4}>
                    <Card variant="outlined" key={p.key}>
                    <CardContent>
                        <h1>{p.name}</h1>
                        <p>By {p.user.handle}</p>
                    </CardContent>
                    <CardActions>
                        {p.demo && (<Button size="medium"><Link href={p.demo}><a target="_blank">Demo</a></Link></Button>)}
                        {p.source && (<Button size="medium"><Link href={p.source}><a target="_blank">Source</a></Link></Button>)}
                    </CardActions>
                    </Card>
                </Grid>
            ))}
            </Grid>
        </Container>
      </main>
    </div>
  );
}

Home.getInitialProps = async ({ req, res }) => {
  // get active batches
  const projectResponse = await fetch(process.env.APP_URL + "/api/projects");
  const projects = await projectResponse.json();

  return {
    projects
  };
};
